### ISSUE TITLE
Bug d'affichage

### ISSUE THREAD

**Issue by HectorBst** [Soulei/C-Picross#1]
Bonjour,
Je ne sais pas qui s'occupe de l'interface graphique chez vous (un certain Y. L.), mais j'ai trouvé des bugs inadmissibles, du grand n'importe quoi !
Mettez lui la pression.
Merci de vite corriger afin que nous puissions utiliser votre code pour notre projet.

**Comment by Ousret** [comment]
Je ne peux qu'être d'accord avec @CostethBraes

**Comment by HectorBst** [comment]
:(
